version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: monthly
      day: saturday
  - commit-message:
      prefix: chore
    directory: /scripts/linkbot/
    package-ecosystem: npm
    schedule:
      interval: monthly
      day: saturday
